language: python
sudo: false
python:
- 2.7
- 3.4
- pypy

before_script:
- bash utils/test_setup.sh

install:
- pip install virtualenv tox docutils coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
